Totodore/socketioxide

Cargo.lock
Readme.md
engineioxide/src/layer.rs
socketioxide/Cargo.toml
socketioxide/src/client.rs
socketioxide/src/extensions.rs
socketioxide/src/lib.rs
socketioxide/src/operators.rs
socketioxide/src/socket.rs

* Removing logs println
* Improving documentation
* Adding Socket Extensions

Socket Extensions + various fixs + docs

---

engineioxide/src/engine.rs
engineioxide/src/errors.rs
engineioxide/src/service.rs

In case of request contains unsupported transport or version, the server replies with code and message according 
[protocol
](https://socket.io/docs/v4/server-instance/)
```
Code | Message
-- | --
0 | "Transport unknown"
1 | "Session ID unknown"
2 | "Bad handshake method"
3 | "Bad request"
5 | "Unsupported protocol version"
```

connection error handling: unsupported version, unsupported transport, bad handshake method

---

.github/workflows/socketio-ci.yml
Cargo.lock
Cargo.toml
Readme.md
e2e/Cargo.toml
e2e/src/engineioxide.rs
e2e/src/socketioxide.rs
engineioxide/src/config.rs
engineioxide/src/engine.rs
engineioxide/src/service.rs
examples/Cargo.toml
examples/src/engineio-echo/axum_echo.rs
examples/src/engineio-echo/hyper_echo.rs
examples/src/engineio-echo/warp_echo.rs
examples/src/socketio-echo/axum_echo.rs
examples/src/socketio-echo/hyper_echo.rs
examples/src/socketio-echo/warp_echo.rs
socketioxide/src/config.rs
socketioxide/src/service.rs

* Adds [socketio-echo/warp_echo.rs](examples/src/socketio-echo/warp_echo.rs)
* Adds [engineio-echo/warp_echo.rs](examples/src/engineio-echo/warp_echo.rs)
* Removes all weird configurations used to test correct protocol implementation with test-suites.
* All test implementations are now in the `e2e` package
* Refactor some unused fn in Service struct

Add Warp usage example & split examples and e2e testing

---

engineioxide/src/errors.rs
engineioxide/src/futures.rs

set content type header.
it's better for client to decode response,  it's good also for debugging using sniffers

Set content-type and charset

---

socketioxide/src/adapter.rs
socketioxide/src/errors.rs
socketioxide/src/handler.rs
socketioxide/src/operators.rs
socketioxide/src/packet.rs
socketioxide/src/socket.rs

fix #27 
create SendError enum, BroadcastError
handle these errors
@Totodore I left todos in places where I don't know how to handle error correctly

handling send to socket error

---

e2e/src/engineioxide.rs
engineioxide/benches/benchmark_polling.rs
engineioxide/src/engine.rs
engineioxide/src/handler.rs
engineioxide/src/layer.rs
engineioxide/src/service.rs
examples/src/engineio-echo/hyper_echo.rs
examples/src/engineio-echo/warp_echo.rs
socketioxide/src/client.rs
socketioxide/src/service.rs

The handler property is never used outside of the `Engine` struct and was behind an `Arc<H>`. 
This adds a layer of indirection for each calls to the handler.
Removing the Arc implies that the `Handler` (and therefore the `Client` struct in the `socketioxide` crate) is created multiple times at startup by the layer (if used with axum for example).

Removing arc from handler property in `Engine`

---

Cargo.lock
examples/src/chat/handlers.rs
socketioxide/src/adapter.rs
socketioxide/src/client.rs
socketioxide/src/errors.rs
socketioxide/src/ns.rs
socketioxide/src/operators.rs
socketioxide/src/socket.rs

Currently the `Adapter` trait was not returning any error. However for future remote adapters it will be necessary.
Therefore the `Adapter` has now a bounded Error type.
For the `LocalAdapter` it is an `Infallible` error.
In order to handle these error without adding generic adapter to all the errors, there is now an error wrapper `AdapterError` which wraps a `Box<dyn std::error>`.

Feature: Error Adapter

---

.github/workflows/engineio-ci.yml

I was just missing the `build` command. I assumed `cargo run` would already build + run the binary, not sure why it doesn't seem to work that way though. Anyways, this commit should fix it.

Fix failing EngineIO CI configuration

---

Cargo.lock
engineioxide/Cargo.toml
engineioxide/src/payload/mod.rs

Upgraded Packet Reader to correctly calculate the packet length when handling Unicode characters. This change was necessary because the previous design would incorrectly size Unicode characters as single bytes. Additional dependency `unicode-segmentation` was introduced to use Unicode segmentation algorithm for correct grapheme counting.
Updated tests to verify the new implementation and made modifications in Cargo.toml and Cargo.lock accordingly. Featured 'v4' and 'v3' were updated to depend on 'unicode-segmentation.'
It still needed to be refactored, but at least it works somehow

Ft improve payload parsing

---

engineioxide/src/config.rs
engineioxide/src/service.rs

This PR adds a field in the `EngineIoConfig` struct so the user is able to specify a limited number of transports, by default all transports are allowed).
For example, only `websocket` requests will be allowed, but `polling` request will be denied with a `400 Bad Request` error.
```rust
let conf = EngineIoConfig::builder()
.transports([TransportType::Websocket])
.build();
```

feat(engineioxide): specific transport restrictions (fix issue #49)

---

Cargo.lock
e2e/Cargo.toml
engineioxide/Cargo.toml
examples/Cargo.toml
socketioxide/Cargo.toml

chore(versioning): v0.4.0

---

socketioxide/src/client.rs
socketioxide/src/ns.rs

This will allow to hide the underlying type : `HashMap<String, EventCallback<A>>`

feat(socketio/ns): create a wrapper struct for NsHandlers and export it

---

e2e/src/socketioxide.rs
engineioxide/src/engine.rs
engineioxide/src/packet.rs
engineioxide/src/socket.rs
socketioxide/src/client.rs
socketioxide/src/config.rs
socketioxide/src/socket.rs

It is used to drop the engine.io connexion if the client **did not send a CONNECT request** to any namespace after the engine.io handshake.
A PR to add this feature to the test-suite has been issued : https://github.com/socketio/socket.io-protocol/pull/31

feat(socketio): connect timeout implementation

---

CHANGELOG.md
Cargo.lock
README.md
e2e/Cargo.toml
engineioxide/Cargo.toml
examples/Cargo.toml
socketioxide/Cargo.toml

* A [`on_disconnect`](https://docs.rs/socketioxide/latest/socketioxide/struct.Socket.html#method.on_disconnect) function is now available on the `Socket` instance. The provided callback will be called when the socket disconnects with the reasons for the disconnection. This is useful for logging or cleanup data.
* A [`connect_timeout`](https://docs.rs/socketioxide/latest/socketioxide/struct.SocketIoConfigBuilder.html#method.connect_timeout) option is now available in the config options. It is the maximum time to wait for a socket.io handshake before closing the connection. The default is 45 seconds.
* A [`NsHandlers`](https://docs.rs/socketioxide/latest/socketioxide/struct.NsHandlers.html) struct was added. It describes namespace handlers passed to the SocketIoLayer/SocketIoService. …

chore: prepare v0.5.0

---

.github/workflows/engineio-ci.yml
.github/workflows/socketio-ci.yml

Use custom ci until PR https://github.com/socketio/socket.io-protocol/pull/33 is merged

chore(ci): migrating from official e2e to custom

---

engineioxide/src/lib.rs
engineioxide/src/packet.rs
engineioxide/src/peekable.rs
engineioxide/src/socket.rs
engineioxide/src/transport/polling/mod.rs
engineioxide/src/transport/polling/payload/encoder.rs
engineioxide/src/transport/polling/payload/mod.rs

This PR apply the `max_payload_size` option to the encoding process for polling. Before, it was only applied when decoding.
In order to calculate the size of the payload with the next packet **without** polling it from the channel, a `PeekableReceiver` struct was made to `peek` the next element without polling it.
For the v3 protocol the current payload computed size is not accurate because the size in `chars` of the packet is included in the payload. And getting that information *before* adding the packet is not possible (also it is a O(n) operation). Therefore the max  packet size length is apply, it is the number of digit of the maximum payload size.

fix: apply max payload option when encoding (fix #113)

---

engineioxide/src/socket.rs
socketioxide/src/client.rs
socketioxide/src/errors.rs
socketioxide/src/ns.rs
socketioxide/src/socket.rs

This PR fix #117 by creating a different socket id for each new namespace socket for the socketio v5 protocol.

fix(socketio/socket): create a different socket id for each ns

---

engineioxide/src/socket.rs
socketioxide/src/client.rs
socketioxide/src/errors.rs
socketioxide/src/ns.rs
socketioxide/src/socket.rs

Reverts Totodore/socketioxide#123
It appears that solving this issue implies a big refactoring. Indeed referencing socketio socket with custom sid instead is impossible because of the following architecture : 
`client recv data from engine socket -> route to corresponding namespace -> route to corresponding socket with <Engine id -> socket> hashmap`
Because the socket id is not in the request it is impossible to map socket by their socket id (and not their engine id).
The solution would be to refactor the code to match the official architecture : 
`client wraps an engine socket and holds a map of the ns -> socket`.

Revert "fix(socketio/socket): create a different socket id for each ns"

---

socketioxide/src/client.rs
socketioxide/src/ns.rs

Thanks to that : 
* The user handler is called only when the connect response is successfully sent trough the channel
* If the socket channel returns an error the socket connection is instantly closed

feat(socketio/ns): improve connect process

---

socketioxide/src/packet.rs

When encoding packet, array should be expanded only when it is not empty. If the array is empty it should be specified like this : `["event", []]` and not `["event"]`

fix(engineio/packet): array expand for packet event only when not empty

---

socketioxide/src/adapter.rs

fix(socketio/adapter): broadcast except current sid when no rooms

---

Cargo.lock
examples/background-task/Cargo.toml
examples/background-task/src/main.rs
socketioxide/src/io.rs
socketioxide/src/operators.rs

Fix: broadcast by default for any `io` operator

---

engineioxide/src/engine.rs
engineioxide/src/lib.rs
engineioxide/src/socket.rs
engineioxide/src/transport/polling/mod.rs
engineioxide/src/transport/ws.rs
socketioxide/src/socket.rs

Because extractors can't contain any reference, making a `Req` extractor would require to clone the `Req` data which is not ideal.

feat(engineio/socket): make init http request available everywhere

---

CHANGELOG.md
Cargo.lock
Cargo.toml
engineioxide/Cargo.toml
engineioxide/src/transport/ws/mod.rs
engineioxide/src/transport/ws/tokio_io.rs
socketioxide/Cargo.toml

Build was broken when using the `hyper-v1` feature flag because of `hyper-util` dependencie which is not published on crates.io

fix: implement manually `tokio_io` module for `hyper v1`

---

Cargo.lock
Cargo.toml
socketioxide/Cargo.toml
socketioxide/benches/itoa_bench.rs
socketioxide/src/packet.rs

socket.io packet encoding with itoa

---

engineioxide/src/service/parser.rs
engineioxide/src/socket.rs
socketioxide/src/handler/extract.rs
socketioxide/src/lib.rs
socketioxide/src/socket.rs

Adds the following function to the `Socket` struct:
* `transport_type` to get the current `TransportType` of the socket
* `protocol` to get the current `ProtocolVersion` of the socket in the case of multiple protocols enabled
Now handler extractors are implemented for `TransportType` and `ProtocolVersion` so now it is possible to use them as `Handler` arguments:
```rust
use socketioxide::{SocketIo, TransportType, ProtocolVersion, extract::*};
let (_, io) = SocketIo::new_svc();
io.ns("/", |socket: SocketRef, transport: TransportType| {
assert_eq!(socket.transport_type(), transport);
});
io.ns("/", |socket: SocketRef, protocol: ProtocolVersion| {
assert_eq!(socket.protocol(), transport);
});
```
Fix issue #177

Transport type and Protocol Version info for `Socket`

---

README.md

Small fix, about the URL of the `chat` example in `README.md`.

fix: use right example link

---

examples/chat/src/main.rs
examples/private-messaging/src/handlers.rs
socketioxide/src/handler/disconnect.rs
socketioxide/src/handler/extract.rs
socketioxide/src/handler/mod.rs
socketioxide/src/layer.rs
socketioxide/src/lib.rs
socketioxide/src/service.rs
socketioxide/src/socket.rs
socketioxide/tests/disconnect_reason.rs

* It will improve API coherence in the socket.io API
* It will be possible to use global managed state provided with #187

Disconnect dynamic handlers

---

CHANGELOG.md
Cargo.lock
Cargo.toml
e2e/socketioxide/socketioxide.rs
socketioxide/Cargo.toml
socketioxide/src/handler/message.rs

Fix async handlers not run

---

Cargo.lock
examples/angular-todomvc/Cargo.toml
examples/angular-todomvc/src/main.rs
examples/basic-crud-application/Cargo.toml
examples/basic-crud-application/src/handlers/todo.rs
examples/basic-crud-application/src/main.rs
examples/chat/Cargo.toml
examples/chat/src/main.rs
examples/private-messaging/Cargo.toml
examples/private-messaging/src/handlers.rs
examples/private-messaging/src/main.rs
examples/private-messaging/src/store.rs
socketioxide/Cargo.toml
socketioxide/src/client.rs
socketioxide/src/handler/extract.rs
socketioxide/src/io.rs
socketioxide/src/lib.rs
socketioxide/src/state.rs
socketioxide/tests/extractors.rs
socketioxide/tests/fixture.rs

Note : Before merging this PR, it is necessary to use dynamics handler for the `on_disconnect` function. Otherwise it wont be possible to use the state in these handlers.
Currently it is not possible to use the references in extractors because of the following problem :
In the `ConnectHandler` implementation below for any function with arguments that implements `FromConnectParts` and are specified by values. To add a lifetime to extractors we could add a lifetime on the trait `FromConnectParts`. The problem is that the provided lifetime should be the one declared with the `for<'a>` corresponding to the function and its scope is rather limited.
```rust
impl<A, F, $($ty,)*> ConnectHandler<A, (private::Sync, $($ty,)*)> for F
where
F: for<'a> FnOnce($($ty,)*) + Send + Sync + Clone + 'static, …
```

feat(socketio/state): global state implementation backed by a `state::TypeMap`

---

Cargo.lock
Cargo.toml
engineioxide/Cargo.toml
engineioxide/src/body.rs
engineioxide/src/service/futures.rs

It will allow to have lighter required deps.

chore(deps): switch to `pin-project-lite` for Pin Projection

---

README.md

I saw Axum versions were in descending order, so I did the same for others :)
Also fixed the version compatibility (Axum 0.7 - Hyper 1.0 - Socketioxide >= 0.9, and Axum 0.6 - Hyper 0.14 - Socketioxide < 0.9)

Fix version compatibility (Axum - Hyper -Socketioxide)

---

README.md

The links to axum 0.6 and 0.7 in README.md are swapped.
Fixed the links.

Fix wrong links to axum in README.md

---

Cargo.toml
README.md
engineioxide/src/service/mod.rs
examples/viz-echo/Cargo.toml
examples/viz-echo/viz_echo.rs
socketioxide/Cargo.toml
socketioxide/benches/packet_decode.rs
socketioxide/benches/packet_encode.rs

Viz supports a [`ServiceHandler`](https://docs.rs/viz/latest/viz/handler/struct.ServiceHandler.html) wrapper to handle socketioxide service in v0.7.

chore: add viz-echo example

---

CHANGELOG.md
Cargo.toml
examples/viz-echo/Cargo.toml
socketioxide/Cargo.toml
socketioxide/src/io.rs
socketioxide/src/operators.rs
socketioxide/src/socket.rs

Also :
* Add better test for `get_socket` fn
* export `Sid` type
* make `get_socket` fn return an `Option<SocketRef>` rather than a private `Error`
* Remove viz from workspace deps because of https://github.com/viz-rs/viz/issues/122

Minor fix + Prepare v0.9.1

---

Cargo.toml
socketioxide/Cargo.toml
socketioxide/tests/extractors.rs
socketioxide/tests/fixture.rs
socketioxide/tests/utils.rs

Integration tests are quite complex without the use of a `socketio` client. 
The  `rust_socketio` lib has been ended to the integration tests and the `extractors` tests have been refactored.

test(socketio): improve testing by directly using the `rust_socketio` client

---

examples/salvo-echo/Cargo.toml
examples/salvo-echo/salvo_echo.rs

Related to discussions : 
* #220

doc(example): add `cors` for `salvo_echo`

---

engineioxide/src/sid.rs

feat(engineio/sid): add `as_str` fn for `Sid`

---

engineioxide/src/transport/ws.rs
socketioxide/src/socket.rs

Before http `1.0` the `Parts` struct was not `clonable` because extensions were not. Because it is now possible, we can now clone the whole `Parts` sruct rather than rebuilding it for the ws transport. 
Therefore it is now possible to retrieve `Extensions` related to the initialized request.
Use `parts.clone()` rather than rebuilding an entire `Request` struct and ommitting the `extensions` field.

Clone http request for ws transport

---

Cargo.toml
socketioxide/Cargo.toml
socketioxide/src/lib.rs
socketioxide/src/operators.rs
socketioxide/src/socket.rs

Document emit variable arguments fn

---

socketioxide/src/extensions.rs

numer -> number
A typo was found
Added a 'b' to correct the typo

doc(socketioxide) typo in extensions::len documentation

---

CHANGELOG.md
Cargo.toml
socketioxide/Cargo.toml
socketioxide/src/adapter.rs
socketioxide/src/io.rs
socketioxide/src/operators.rs

feat(socketio/operators): get all rooms from `io`

---

socketioxide/src/client.rs

Under heavy traffic, some desynchronisation between events might happen and then lead to panic with the connect timeout mechanism.
If a ns connect message is received, we stop the connect timeout task. But if the connect timeout task has been triggerred in the meantime the `Receiver` is dropped and the `Sender` will panic because we unwrap the send error `tx.send(()).unwrap();`.
Discard the error like that `tx.send(()).ok();`

fix(socketio/client): connect timeout panic under heavy traffic

---

e2e/socketioxide/socketioxide.rs
engineioxide/src/socket.rs
examples/private-messaging/Cargo.toml
examples/private-messaging/src/handlers.rs
socketioxide/src/ack.rs
socketioxide/src/adapter.rs
socketioxide/src/errors.rs
socketioxide/src/handler/extract.rs
socketioxide/src/io.rs
socketioxide/src/lib.rs
socketioxide/src/operators.rs
socketioxide/src/packet.rs
socketioxide/src/socket.rs
socketioxide/tests/acknowledgement.rs

> There are two remaining questions :
> * What should be done with binary packets. Because a message can contain N binary payloads it means that we would need N+1 Permits for each emit call.
> * What should be done when broadcasting. What is the performance cost of asking X Permits from N sockets at the same time ? Because packet is encoded only once and then cloned many times to be sent. Maybe it would be better to just clone the data before sending anything so it is possible to send it back to the user.
Also broadcasting is done through Operators, and Operators are not always used to broadcast, they can be used to simply add a timeout or a binary payload when emitting. So the emit signature needs to be the same from the Operator fn even if it is not broadcasting.
* The new …

Return emitted data in case of emission error.

---

CHANGELOG.md
Cargo.toml
socketioxide/Cargo.toml

* fix: a panic was raised sometimes under heavy traffic with socketio v5 when the connect timeout handler is destroyed but that the chan sender is still alive.
* **(Breaking)**: Emit errors now contains the provided data if there is an issue with the internal channel (for example if it is full) or if the socket closed.
* **(Breaking)**: Operators are now splitted between `Operators` and `BroadcastOperators` in order to split logic and fn signatures between broadcast and non-broadcast operators.
* fix #277: with engine.io v3, the message byte prefix `0x4` was not added to the binary payload with `ws` transport.
* bump dependency `base64` to 0.22.0.

chore(deps): bump to v0.11

---

engineioxide/Cargo.toml
engineioxide/src/socket.rs
engineioxide/src/transport/polling/payload/encoder.rs
engineioxide/src/transport/polling/payload/mod.rs
engineioxide/src/transport/ws.rs
socketioxide/src/handler/extract.rs
socketioxide/src/operators.rs
socketioxide/src/packet.rs
socketioxide/src/socket.rs
socketioxide/tests/concurrent_emit.rs
socketioxide/tests/fixture.rs

* Fix #232 
Change the engine.io socket internal channel so that it can take multiple packets at once. It is backed by [smallvec](https://docs.rs/smallvec/latest/smallvec/) which allows to put packets on the stack for small sizes before moving to the heap. This will avoid slowdowns where there is only one packet sent (most of the time).

fix(engineio/socket): atomically adjacent packet requirement for binary payloads

---

.github/workflows/github-ci.yml
CONTRIBUTING.md
Cargo.toml
engineioxide/Cargo.toml
engineioxide/src/lib.rs
engineioxide/src/socket.rs
examples/Cargo.toml
examples/salvo-echo/Cargo.toml
socketioxide/Cargo.toml
socketioxide/src/client.rs
socketioxide/src/io.rs
socketioxide/src/ns.rs
socketioxide/src/socket.rs
socketioxide/tests/acknowledgement.rs
socketioxide/tests/concurrent_emit.rs
socketioxide/tests/connect.rs
socketioxide/tests/extractors.rs
socketioxide/tests/fixture.rs
socketioxide/tests/utils.rs

* Add a custom `new_dummy_socket` with tx/rx to send and receive packet without creating a real connexion.
* Remove dep `socket_io` client.
* Remove the feature `test-utils` in favor of a rust cfg flag `socketioxide-test`
* Move all the examples to a separate workspace to avoid dependency bloat / useless checks when working on socketioxide. A separate job actions in now dedicated to checking the example code.

tests: Improve test bed

---

Cargo.toml
e2e/engineioxide/Cargo.toml
e2e/engineioxide/engineioxide.rs
engineioxide/Cargo.toml
engineioxide/Readme.md
engineioxide/src/config.rs
engineioxide/src/engine.rs
engineioxide/src/handler.rs
engineioxide/src/layer.rs
engineioxide/src/packet.rs
engineioxide/src/service/mod.rs
engineioxide/src/socket.rs
engineioxide/src/transport/polling/payload/decoder.rs
engineioxide/src/transport/polling/payload/encoder.rs
engineioxide/src/transport/polling/payload/mod.rs
engineioxide/src/transport/ws.rs
engineioxide/tests/disconnect_reason.rs
socketioxide/Cargo.toml
socketioxide/src/ack.rs
socketioxide/src/client.rs
socketioxide/src/handler/extract.rs
socketioxide/src/handler/message.rs
socketioxide/src/io.rs
socketioxide/src/operators.rs
socketioxide/src/packet.rs
socketioxide/src/socket.rs
socketioxide/tests/concurrent_emit.rs
socketioxide/tests/connect.rs

As requested, moved to a separate PR :)

Use bytes::Bytes instead of Vec<u8> to represent binary payloads

---

Cargo.toml
socketioxide/Cargo.toml
socketioxide/src/layer.rs

The salvo dep introduce **A lot** of dependencies and it is only use for a small doc example.
Because there is real example in the example folder it is better to remove it to lighten the dev env.

chore: remove salvo deps and corresponding doctest

---

Cargo.toml
e2e/heaptrack/Cargo.toml
engineioxide/Cargo.toml
examples/Cargo.toml
examples/hyper-echo/Cargo.toml
socketioxide/Cargo.toml

With hyper [`1.0.3`](https://github.com/hyperium/hyper/blob/master/CHANGELOG.md#v130-2024-04-15). The `hyper::Service` is exposed without any feature flag. Meaning that we can remove ("server", "http1", "http2"), from the main package (they will only be used in the dev deps.

chore(deps): bump hyper to "1.0.3" and remove unused features

---

e2e/engineioxide/engineioxide.rs
engineioxide/Readme.md
engineioxide/benches/packet_decode.rs
engineioxide/benches/packet_encode.rs
engineioxide/src/config.rs
engineioxide/src/engine.rs
engineioxide/src/handler.rs
engineioxide/src/layer.rs
engineioxide/src/lib.rs
engineioxide/src/packet.rs
engineioxide/src/service/mod.rs
engineioxide/src/socket.rs
engineioxide/src/str.rs
engineioxide/src/transport/polling/payload/decoder.rs
engineioxide/tests/disconnect_reason.rs
socketioxide/src/client.rs
socketioxide/src/packet.rs
socketioxide/tests/acknowledgement.rs
socketioxide/tests/connect.rs
socketioxide/tests/extractors.rs

Currently the `Message` packet variant is backed by a `String`. This leads to a useless data clone when slicing to remove the first byte (the engineio packet type).
The `Str` type is backed by a `Bytes` and therefore can be sliced into any number of sub-Bytes.

feat(engineio): add a `Str` type for Message packet

---

socketioxide/src/client.rs
socketioxide/src/io.rs
socketioxide/src/ns.rs
socketioxide/src/socket.rs
socketioxide/tests/connect.rs
socketioxide/tests/disconnect_reason.rs

* Gracefully close the namespace rather than just removing it. Meaning that the corresponding namespace adapter will be closed as well as all the sockets in the namespace. Their `disconnect_handler` will be called with a `ServerNSDisconnect` reason.
* Fix deadlock when deleting the namespace from inside a `disconnect_handler`.
Fixes :
* #311

Fix: deadlocking when calling `close_ns` from inside a `disconnect_handler`

---

CHANGELOG.md
Cargo.toml
socketioxide/Cargo.toml

* fix: issue #311, the `delete_ns` fn was deadlocking the entire server when called from inside a `disconnec_handler`.
* feat: the `delete_ns` is now gracefully closing the adapter as well as all its sockets before being removed.
* feat: the API use `Bytes` rather than `Vec<u8>` to represent binary payloads. This allow to avoid unnecessary copies.
* deps: use `futures-util` and `futures-core` rather than the whole `futures` crate.
* feat: the API use `Bytes/Str` rather than `Vec<u8>` and `String` to represent payloads. This allow to avoid unnecessary copies.
* deps: use `futures-util` and `futures-core` rather than the whole `futures` crate.

Socketioxide v0.13.0

---

engineioxide/src/transport/ws.rs

fix(engineio/ws): remove unecessary panic message when receiving unexpected ws packets

---

CHANGELOG.md
Cargo.toml
socketioxide/Cargo.toml

* fix: issue #320. Remove unnecessary panic when receiving unexpected websocket messages. This might happen with some specific socket.io clients.

chore: bump version to v0.13.1

---

socketioxide/Cargo.toml
socketioxide/src/extensions.rs
socketioxide/src/lib.rs
socketioxide/src/socket.rs

chore(deps): remove useless dashmap dep and improve doc

---

.github/workflows/bencher.yml

Disable bench on PR as the bench targets only a subset of the features of socketioxide which are often not modified in PRs (such as packet encoding/decoding).

chore(ci): bench only on main and on manual trigger

---

engineioxide/src/str.rs
socketioxide/src/client.rs
socketioxide/src/extract/socket.rs
socketioxide/src/packet.rs
socketioxide/src/socket.rs
socketioxide/tests/connect.rs
socketioxide/tests/extractors.rs

Currently the namespace path is decoded from a `Str` payload, meaning that we can extract it in a zero copy manner by slicing the `Str` and storing it like that.
It also fixes a lifetime issue for PR #333 with path params. Because the path need to outlive the decoded params from the matchit router as long as they are not decoded by the user.
* Switch the namespace path to a `Str`.
* Add some implementation of `From` for `Str` for the construction of new outgoing packets.

feat(socketio/packet): switch to `Str` type for ns path storage

---

engineioxide/src/str.rs
socketioxide/src/client.rs

Most of the Namespace paths are now `Str`. It allows to avoid lifetime issue and reduce allocations. To match the use of `Str` in the codebase we can also switch from a `Hashmap<Cow<'static, str>, Namespace>` to a `Hashmap<Str, Namespace>`. Thanks to that there is not only no copying when using `'static str` (this was already the case) but also when using owned `String`. For example with dynamic namespaces or when the user provide owned strings.
Fixes also a minor memory leak where namespaces created from dynamic namespaces were keeping a ref to the namespace path in the connect packet. Thus never freeing the packet.

feat: Namespace key in map as `Str`

---

CHANGELOG.md
Cargo.toml
socketioxide/Cargo.toml
socketioxide/src/extract/mod.rs
socketioxide/src/io.rs

* **(Breaking)**: State reworked to avoid having unsafe global mutable state (issue [#317](https://github.com/Totodore/socketioxide/issues/317)). Therefore State types must now implement `Clone` and will be cloned for each handler where the state is used.
* **(Breaking)**: Extensions reworked to avoid `Send` + `Sync` requirements on extensions (issue [#295](https://github.com/Totodore/socketioxide/issues/295)). They are now extracted by `Cloning`. Therefore all the type must implement `Clone`. An `Extension` extractor is available to get an extension directly without calling `socket.extensions.get()`.
* feat: New `HttpExtension` types to extract extensions from the http request.
* feat: `SocketIo` can now be used as an extractor. So you can now easily access the entire socket.io context …

chore(deps): v0.14.0

---

socketioxide/src/io.rs

Add generics to the function signatures for the `build_*` fns to propagate with adapter set with `with_adapter` function.

fix(socketio/io): adapter builder

---

e2e/heaptrack/src/client.rs
engineioxide/benches/packet_encode.rs
engineioxide/src/transport/polling/payload/decoder.rs
engineioxide/src/transport/polling/payload/mod.rs
engineioxide/tests/fixture.rs
socketioxide/benches/packet_decode.rs
socketioxide/benches/packet_encode.rs
socketioxide/src/ack.rs
socketioxide/src/client.rs
socketioxide/src/packet.rs
socketioxide/src/socket.rs
socketioxide/tests/acknowledgement.rs
socketioxide/tests/connect.rs
socketioxide/tests/disconnect_reason.rs
socketioxide/tests/extractors.rs
socketioxide/tests/fixture.rs

The `clippy` has some tips.
Modify the codes according to the `clippy` tips.

refactor(test): cargo clippy

---

.github/workflows/github-ci.yml

[E2e scripts](https://github.com/totodore/socket.io-protocol) have been updated and they now use the default `fetch` implementation in node which is not available in v16.

chore(ci): switch from node v16 to node v22 for e2e testing

---

crates/socketioxide/src/handler/message.rs

Fix #375 
Tracing errors where missing when using extractors in async message handlers.
Add the missing error logs.

fix(socketio/handler): trace extractor errors

---

crates/socketioxide-core/src/lib.rs
crates/socketioxide/src/extract/mod.rs
crates/socketioxide/src/handler/mod.rs

Related to #374.
Slightly improve doc for extractors and re-export the `socketioxide_core::Value` type.

doc(socketio): improve extractor docs

---

CHANGELOG.md
Cargo.toml
crates/parser-common/Cargo.toml
crates/parser-msgpack/Cargo.toml
crates/socketioxide-core/Cargo.toml
crates/socketioxide/Cargo.toml

* **(Breaking)**: New parsing system. You can now serialize and deserialize binary data inside your own types.
It also improve performances by avoiding unnecessary allocations.
* fix: missing extractor error logs for async message handlers.
* feat: add custom compiler error for unimplemented handler traits.
* deps: switch from `tower` to `tower-service` and `tower-layer` subcrates.
* deps: bump `tokio` to 1.40.
* deps: bump `http` to 1.1.
* deps: bump `hyper` to 1.5.

chore(deps): prepare v0.15.0

---

crates/engineioxide/src/socket.rs
crates/socketioxide/Cargo.toml

Fixes:
* #390
First ping is sent two times because tokio interval default mode is `Bursting`. Because the first tick is missed, the next one is sent two times.
Initiate the tokio interval struct _after_ the initial delay

fix(engineio/socket): heartbeat delay causing ping burst

---

crates/socketioxide/src/io.rs

The `SocketIo` struct was lacking a `broadcast` operator that would default to broadcasting to every socket in the default namespace `/`.
Add a `broadcast()` operator.

feat(socketio): add broadcast operator on `io` struct

---

crates/socketioxide-core/src/adapter.rs
crates/socketioxide/src/ack.rs
crates/socketioxide/src/client.rs
crates/socketioxide/src/ns.rs

* Improve `broadcast_with_ack` implementation.
* Use a custom iterator for `apply_opts` return type to avoid extra allocations.

feat(socketio/ns): improve `SocketEmitter` trait

---

crates/socketioxide-core/src/lib.rs
crates/socketioxide/src/extract/mod.rs
crates/socketioxide/src/extract/socket.rs
crates/socketioxide/src/handler/connect.rs
crates/socketioxide/src/handler/disconnect.rs
crates/socketioxide/src/handler/message.rs
crates/socketioxide/src/io.rs
crates/socketioxide/src/lib.rs

* Add more details on adapters on the docs home page
* Add error case for the `unimplemented` compiler hint for handlers.
* Add more details about adapters for extractors.

chore(docs): add documentation for async adapters

---

crates/socketioxide-core/src/adapter.rs
crates/socketioxide-core/src/errors.rs
crates/socketioxide/docs/operators/emit_with_ack.md
crates/socketioxide/docs/operators/fetch_sockets.md
crates/socketioxide/docs/operators/get_socket.md
crates/socketioxide/docs/operators/rooms.md
crates/socketioxide/docs/operators/sockets.md
crates/socketioxide/src/ack.rs
crates/socketioxide/src/adapter.rs
crates/socketioxide/src/client.rs
crates/socketioxide/src/io.rs
crates/socketioxide/src/ns.rs
crates/socketioxide/src/operators.rs
crates/socketioxide/src/socket.rs

When working with remote adapter we need a way to manage remote sockets, fetch them and use them (emit, join, leave, disconnect ,etc...).
The `Adapter` trait has a new `fetch_sockets(BroadcastOptions)` function that allow the user to get a `RemoteSocket`. The `RemoteSocket` implements a subset of the `Socket` API. He can then get informations about the remote socket (id, server_id, namespace) and use functions like `emit`/`join`/`leave`/`disconnect`.
Internally the actions on the `RemoteSocket` are propagated through the adapter with a `BroadcastOptions` that contains uniquely the sender socket id.
The `rooms` operator is also modified to take into account the `BroadcastOptions` rather than always fetching all the rooms.

feat(adapter): add a remote socket API

---

crates/socketioxide-core/src/adapter.rs
crates/socketioxide-core/src/lib.rs
crates/socketioxide/src/io.rs
crates/socketioxide/src/ns.rs

To avoid bugs, the server id type should not be the same that the socket (`Sid`).
A new wrapper type named `Uid` will define a server id.

feat(core): switch to a new type for server `Uid`

---

Cargo.toml
crates/engineioxide/src/transport/ws.rs
crates/socketioxide/tests/disconnect_reason.rs
crates/socketioxide/tests/fixture.rs
examples/react-rooms-chat/Cargo.toml

* Use new tokio-tungstenite `Message` API with `Bytes` rather than owned `Vec`. Thanks to that we have much less allocations when reading/writing to websockets. 
* Switch from `TryFrom<Packet> for String` to `From<Packet> for String` because there is no errors when serializing a packet to a string.

Bump tokio tungstenite to 0.26

---

e2e/engineioxide/test-suites/v4.ts
e2e/socketioxide/test-suites/package-lock.json
e2e/socketioxide/test-suites/v5-msgpack.ts
e2e/socketioxide/test-suites/v5.ts

In case of http polling heartbeat timeout, engine.io might send a close packet to an existing polling connection before closing. Fix the test for this case.

chore(ci/e2e): fix polling ping timeout test

---

crates/engineioxide/src/socket.rs
crates/engineioxide/tests/disconnect_reason.rs
crates/socketioxide/src/client.rs
crates/socketioxide/tests/disconnect_reason.rs
crates/socketioxide/tests/fixture.rs
e2e/engineioxide/test-suites/v4.ts
e2e/socketioxide/socketioxide.rs
e2e/socketioxide/test-suites/package-lock.json
e2e/socketioxide/test-suites/v5-msgpack.ts
e2e/socketioxide/test-suites/v5.ts

A delay was arbitrarily before starting the engine.io heartbeat when the socket is connecting.
The goal was mostly to comply with the socket.io test suite which was
not checking the ping packet before doing other operations.
With the js implementation it is OK because it is slow.
But it was causing issue with this one.

fix(engineio): heartbeat delay

---

.github/workflows/github-ci.yml
crates/socketioxide-redis/src/lib.rs
crates/socketioxide-redis/src/stream.rs
crates/socketioxide/src/ack.rs
crates/socketioxide/src/client.rs
crates/socketioxide/src/extract/socket.rs
crates/socketioxide/src/socket.rs
e2e/adapter/client.ts
e2e/adapter/fixture.ts
e2e/adapter/package.json
e2e/adapter/src/lib.rs
e2e/engineioxide/test-suites/v3.ts
e2e/socketioxide/test-suites/v4.ts

* Improve the adapter test-suite to cover a lot more cases.
* Fix issues on redis adapter:
* The ack stream was closed if the remote part was closed without checking the local one.
* The expected response count when waiting for responses was set to server count even when sending the request to a single server leading to waiting for the timeout before getting the response.
* Fix issue on `RemoteSocket` struct, the `impl RoomParam` lifetime was bound to the async function for `leave` and `join` fns. Therefore it was impossible to use `&'static str` whereas `RoomParam` is implemented for `&'static str`.
* Manual implementation for some `Clone` and `Debug` to avoid automatic bound on generic adapter.

Test redis adapter

---

.github/workflows/release.yml
CHANGELOG.md
Cargo.toml
crates/engineioxide/Cargo.toml
crates/parser-common/Cargo.toml
crates/parser-msgpack/Cargo.toml
crates/socketioxide-core/Cargo.toml
crates/socketioxide-redis/Cargo.toml
crates/socketioxide/Cargo.toml
e2e/engineioxide/Cargo.toml
e2e/socketioxide/Cargo.toml

* Socketioxide has a new logo!
* Remote adapters are finally here! You can use them to scale your socket.io application easily. 
See [this article](https://github.com/Totodore/socketioxide/discussions/440) for more info.
* Thanks to @dollannn and @BrianWiz for their sponsoring!
_From now all crate versions are disjoined._
* feat(*breaking*): remote adapters, see [this article](https://github.com/Totodore/socketioxide/discussions/440) for more details.
* deps: bump `thiserror` to 2.0
* deps: bump `axum` to 0.8
* deps: bump `engineioxide` to 0.16.0
* docs: fix grammar/typos
* feat(*breaking*): remote adapters
* feat(*breaking*): remote adapters
* feat(*breaking*): remote adapters
* Initial release!
* deps: bump `thiserror` to 2.0
* deps: bump `tokio-tungstenite` to 0.26
* docs: fix …

chore(deps): prepare v0.16

---

crates/engineioxide/src/service/mod.rs
crates/engineioxide/src/transport/ws.rs
crates/engineioxide/tests/disconnect_reason.rs
crates/engineioxide/tests/fixture.rs

Integration tests are currently done by spawning hyper server and issuing http request on it (which can be later upgraded to ws).
Hence, it's more e2e testing than integration testing by definition.
Mock http connections and mock ws connections so that we can send request to the `EngineioService` without actually spawning an http server.

test(engineio): mock http/ws connections and improve integration tests

---

crates/engineioxide/src/service/mod.rs
crates/engineioxide/src/transport/ws.rs
crates/engineioxide/tests/disconnect_reason.rs
crates/engineioxide/tests/fixture.rs

Reverts Totodore/socketioxide#444.
Not properly implemented due to incorrect `AsyncRead` implementation.

Revert "test(engineio): mock http/ws connections and improve integration tests"

---

crates/socketioxide-redis/Cargo.toml
crates/socketioxide-redis/src/drivers/redis.rs
crates/socketioxide-redis/src/lib.rs
e2e/adapter/src/bins/redis_cluster.rs
examples/chat/src/redis/redis_cluster.rs
examples/redis-whiteboard/src/redis_cluster.rs

Bump redis to 0.28.2 and resolve issue #449

feat(redis): use `ClusterClient` for redis cluster creation

---

CHANGELOG.md
crates/engineioxide/Cargo.toml
crates/parser-common/Cargo.toml
crates/socketioxide-redis/Cargo.toml
crates/socketioxide/Cargo.toml

* feat: add `Config::ws_read_buffer_size` to set the read buffer size for each websocket.
It will default to 4KiB (previously 128KiB). You can increase it if you have high message throughput and less sockets.
* feat: add `Config::ws_read_buffer_size` to set the read buffer size for each websocket.
* deps: bump `engineioxide` to 0.16.1.
* fix: clone partial packets when keeping them to avoid holding a reference to the ws read buffer for too long. Otherwise it cause the ws read buffer to grows indefinitely in a many binary packets scenario.
* deps: bump `redis` to 0.28.2
* feat(*breaking*): the redis cluster adapter constructor now takes a `&redis::cluster::ClusterClient`
to match all other adapter constructors.

Prepare release v0.16.1

---

Cargo.toml
crates/engineioxide/Cargo.toml
crates/socketioxide/Cargo.toml
crates/socketioxide/src/service.rs
crates/socketioxide/tests/disconnect_reason.rs
crates/socketioxide/tests/fixture.rs

Use the new `ws_init` provided by engineioxide to correctly mock http/ws connections without spawning real servers.

test(socketio): mock http/ws connections

---

crates/engineioxide/benches/packet_encode.rs

PR #468 introduced a small breaking change on the `Sid` type which caused a compilation error on an engine.io benchmark.

fix(engineio/bench): fix breaking change from #468

---

.github/workflows/release.yml
CHANGELOG.md
Cargo.lock
README.md
crates/engineioxide/Cargo.toml
crates/engineioxide/src/lib.rs
crates/socketioxide-core/Cargo.toml
crates/socketioxide-redis/Cargo.toml
crates/socketioxide/Cargo.toml

* New crate to share engineioxide core types.
* fix: pause heartbeat when the socket is being upgraded to avoid the client
from resending polling requests to respond to ping packets.
* deps: use engineioxide-core 0.1 as a dependency
* doc: add an incompatibility warning with the `@socket.io/redis-adapter` package.
* deps: use engineioxide-core 0.1 rather than engineioxide
* deps: bump engineioxide to 0.16.2

Release v0.16.2

---

crates/socketioxide/src/extract/data.rs
crates/socketioxide/src/extract/mod.rs
crates/socketioxide/src/socket.rs
crates/socketioxide/tests/extractors.rs

There is currently no way do dynamically handle events. (See issue #498).
The Socket.io JS implementation has catch-all handlers however I don't think it is a good design for socketioxide as it adds a lot of complexity (see the complete list of variant to cover all cases: https://socket.io/docs/v4/listening-to-events/#catch-all-listeners).
A simple `on_fallback` handler that will be called for *unknown* events like a HTTP 404 handler.
A new `Event` extractor will be also available to extract the event name. 
This let the user manage events as he wants and we avoid a lot of complexity that would be introduced by `catch-all` handlers.
> This does not replace the need for a middleware feature with wrapping capabilities, however it is a much bigger task. I will add a tracking issue for this.

feat(socketio): on_fallback handler and Event extractor

---

Cargo.lock
crates/socketioxide/CHANGELOG.md
crates/socketioxide/Cargo.toml
crates/socketioxide/src/client.rs
crates/socketioxide/src/io.rs
crates/socketioxide/src/operators.rs

* feat: add `SocketIo::nsps` to get a list of operators on all the current namespaces.
* feat: add `BroadcastOperators::ns_path` to get the namespace path of the current namespace.
* feat: implement `Debug + Clone` for `BroadcastOperators` to reuse it easily.

feat(socketio): add utility methods

---

Cargo.toml
crates/engineioxide/src/packet.rs
crates/engineioxide/src/service/parser.rs

This PR fixes #547 
On another note, as per the contributing guide, I ran the test suite, which threw some errors.
I believe this cannot be related to my changes, I just thought I mention it here anyway:
```
~/engine.io-protocol/test-suite main ❯ npm test
> engine.io-protocol-test-suite@0.0.1 test
> mocha test-suite.js
Engine.IO protocol
handshake
HTTP long-polling
✔ successfully opens a session
✔ fails with an invalid 'EIO' query parameter
✔ fails with an invalid 'transport' query parameter
✔ fails with an invalid request method
WebSocket
✔ successfully opens a session
✔ fails with an invalid 'EIO' query parameter
✔ fails with an invalid 'transport' query parameter
message
HTTP long-polling
1) sends and receives a payload containing one plain text packet
2) sends and receives a payload …
```

feat(engineio): improve `engineioxide::OpenPacket` serde impl

---

Cargo.lock
crates/engineioxide/src/transport/polling/payload/mod.rs
e2e/engineioxide/test-suites/v3.ts
e2e/engineioxide/test-suites/v4.ts
e2e/socketioxide/test-suites/v4.ts
e2e/socketioxide/test-suites/v5-msgpack.ts
e2e/socketioxide/test-suites/v5.ts

Fix a bug introduced in #554, the `NOOP` packet sent in case of polling request while upgrading was incorrectly encoded as binary for v3 sockets with binary supports.

fix(engineio/v3): incorrect `NOOP` packet formating when upgrading

---

crates/engineioxide/src/socket.rs
e2e/engineioxide/test-suites/v3.ts
e2e/engineioxide/test-suites/v4.ts

#487 introduced a socket upgrade fix. While upgrading the heartbeat process would be paused. However the v3 upgrade process was skipped.

fix(engineio/v3): pause heartbeat while upgrading
