Totodore/socketioxide

.github/workflows/socketio-ci.yml, .vscode/settings.json, engineioxide/src/engine.rs, engineioxide/src/layer.rs, socketioxide/src/adapter.rs
This PR includes : 
* VSCode format on save as a default workspace setting
* rust fmt check in CI script
=> Set up code formatting

engineioxide/src/socket.rs
From the v3 protocol spec:
> Since the two values are shared between the server and the client, the server will also be able to detect whether the client becomes unresponsive when it does not receive any data within pingTimeout + pingInterval.
=> Fix invalid ping timeout in v3 protocol

socketioxide/src/config.rs, socketioxide/src/lib.rs
=> fix(socketioxide): socket.io config for custom transport list

socketioxide/src/packet.rs
Add tests for all the socket.io packets types.
Fix a bug with binary packets with namespaces : namespace was put before the payload count whereas it should be put after according to the payload datagram : 
```
<packet type>[<# of binary attachments>-][<namespace>,][<acknowledgment id>][JSON-stringified payload without binary]
+ binary attachments extracted
```
=> Test: Add test suite for socket.io packet encoding

engineioxide/src/engine.rs
If the polling connection needed to get a noop packet is not made in time (before the end of the upgrade handshake). The NOOP packet will then be sent trough the websocket and cause an protocol error.
To fix this issue the handler that send the packets between the buffer and the websocket filter out all Noop packets.
This PR also improve logging.
=> fix(engine.io): data race for the noop packet

engineioxide/src/body.rs, engineioxide/src/futures.rs, engineioxide/src/payload/buf.rs, engineioxide/src/payload/encoder.rs, engineioxide/src/service.rs, engineioxide/src/sid_generator.rs, engineioxide/src/socket.rs, socketioxide/src/extensions.rs, socketioxide/src/service.rs
No major changes, just cleanups.
=> refactor: Minor optimization and fixes

socketioxide/src/adapter.rs
=> fix(clippy): issue #104

Cargo.lock, e2e/engineioxide/engineioxide-hyper-v04.rs, e2e/engineioxide/engineioxide-hyper-v1.rs, engineioxide/Cargo.toml, engineioxide/Readme.md, engineioxide/src/config.rs, engineioxide/src/engine.rs, engineioxide/src/handler.rs, engineioxide/src/lib.rs, engineioxide/tests/disconnect_reason.rs, socketioxide/src/client.rs
=> chore(deps): remove unused `async_trait` deps

Cargo.lock, Cargo.toml, engineioxide/Cargo.toml, engineioxide/benches/packet_decode.rs, engineioxide/benches/packet_encode.rs, engineioxide/src/errors.rs, engineioxide/src/lib.rs, engineioxide/src/packet.rs, engineioxide/src/socket.rs, socketioxide/Cargo.toml, socketioxide/src/socket.rs
=> Optimize `engineio` packets processing

socketioxide/src/io.rs
`with_adapter` fn for `SocketIoBuilder` to replace all the `build_***_with_adapter` fns.
=> Improve adapter configuration

.github/ISSUE_TEMPLATE/config.yml
Add the socketioxide channel into the issue menu
=> doc: add tokio discordl ink

socketioxide/src/adapter.rs, socketioxide/src/io.rs, socketioxide/src/ns.rs, socketioxide/src/operators.rs
=> feat: get a socket by the specified sid

Cargo.toml, examples/viz-echo/Cargo.toml
fixes: https://github.com/viz-rs/viz/issues/122
=> fix: compile viz-echo

examples/viz-echo/Cargo.toml, examples/viz-echo/viz_echo.rs
Update Viz to [0.8.0](https://github.com/viz-rs/viz/releases/tag/v0.8.0)
Serve a server with graceful shutdown
=> chore(deps): viz 0.8.0

.github/workflows/github-ci.yml, .github/workflows/release.yml
=> chore(ci): add release pipeline

.github/workflows/github-ci.yml, .github/workflows/release.yml
* Execute doctests in parallel
* Directly release from main branch rather than release branch
=> fix: Release ci

engineioxide/src/transport/ws.rs
In v3 of the engine.io protocol, the packet type byte is prepended to the binary data that is sent out on a websocket binary frame.  This byte needs to be stripped off the data before it's sent to the handler.
Closes #277.
=> Fix extra byte in websocket binary frame on EIO v3

examples/webrtc-node-app/Cargo.toml, examples/webrtc-node-app/README.md, examples/webrtc-node-app/public/client.js, examples/webrtc-node-app/public/index.html, examples/webrtc-node-app/src/main.rs
Improve documentation and close issue #347
=> doc(example): add webrtc example

Cargo.toml, socketioxide/Cargo.toml
* fix(#357): infinite loop when receiving malformed binary packet. Thanks to @yhx-12243 for finding and fixing the bug.
=> chore(deps): v0.14.1

Cargo.toml, crates/engineioxide/Cargo.toml, crates/engineioxide/src/layer.rs, crates/engineioxide/src/service/mod.rs, crates/parser-common/Cargo.toml, crates/parser-msgpack/Cargo.toml, crates/socketioxide/Cargo.toml, crates/socketioxide/src/layer.rs, crates/socketioxide/src/service.rs, e2e/socketioxide/socketioxide.rs, examples/Cargo.toml
* Upgrade all dependencies to latest.
* Use specific sub-crate `tower-layer` and `tower-service` rather than full tower lib.
=> chore: bump deps and switch to `tower-layer` and `tower-service` rather than `tower`

crates/socketioxide-core/src/adapter.rs, crates/socketioxide-core/src/lib.rs, crates/socketioxide/src/socket.rs
Add a reverse datastructure `HashMap<Sid, HashSet<Room>>` to improve performance on some local adapter operations.
=> feat(core/adapter): improve perf for local adapter

Cargo.toml, crates/engineioxide/src/transport/ws.rs
Reverts Totodore/socketioxide#427
=> Revert "Bump tokio tungstenite to 0.26"

.github/logo_dark.svg, .github/logo_light.svg, README.md, crates/socketioxide-redis/README.md, crates/socketioxide-redis/src/lib.rs, crates/socketioxide/src/lib.rs, examples/Cargo.toml, examples/chat/Cargo.toml, examples/chat/README.md, examples/chat/Readme.md, examples/chat/src/main.rs, examples/chat/src/redis/redis.rs, examples/chat/src/redis/redis_cluster.rs, examples/chat/src/redis/redis_fred.rs
* Add a readme for the redis crate and chat examples.
* Add the socketioxide icon on the README.
=> doc(redis): add doc and examples

.github/workflows/github-ci.yml, crates/socketioxide-redis/Cargo.toml, e2e/adapter/client.ts, e2e/adapter/package.json, e2e/adapter/tsconfig.json, e2e/engineioxide/test-suites/.gitignore, e2e/engineioxide/test-suites/package-lock.json, e2e/engineioxide/test-suites/package.json, e2e/engineioxide/test-suites/utils.ts, e2e/engineioxide/test-suites/v3.ts, e2e/engineioxide/test-suites/v4.ts, e2e/socketioxide/test-suites/.gitignore, e2e/socketioxide/test-suites/package-lock.json, e2e/socketioxide/test-suites/package.json, e2e/socketioxide/test-suites/utils.ts, e2e/socketioxide/test-suites/v4.ts, e2e/socketioxide/test-suites/v5-msgpack.ts, e2e/socketioxide/test-suites/v5.ts
Rewrite e2e test-suites with default node test suite.
Move the test-suites to this repo.
* Fixes #424
=> Move e2e test suites to this repo

crates/engineioxide/src/socket.rs, e2e/engineioxide/test-suites/v3.ts, e2e/engineioxide/test-suites/v4.ts
This reverts commit 16098ce484d29af8921226a6a295a1592df49dcb.
=> Revert "fix(engineio/v3): pause hb while upgrading (#575)"

README.md, crates/engineioxide/src/socket.rs, examples/Cargo.lock, examples/warp-echo/Cargo.toml, examples/warp-echo/warp_echo.rs
Warp now supports Hyper V1.0, add a socketioxide integration example.
=> examples(warp): add latest warp example
